export const citySuggestions = [
  'New York',
  'Los Angeles',
  'Chicago',
  'London',
  'Paris',
  'Berlin',
  'Tokyo',
  'Osaka',
  'Singapore',
  'Dubai',
  'Mumbai',
  'Delhi',
  'Bengaluru',
  'Sydney',
  'Melbourne',
  'Toronto',
  'Vancouver',
  'Cape Town',
  'Seoul',
  'Bangkok',
  'Istanbul',
  'Rome',
  'Madrid',
  'Barcelona',
  'Amsterdam',
  'Cairo',
  'Rio de Janeiro',
  'Buenos Aires',
  'Jakarta',
  'Karachi',
];
